const restaurants = [
  {
    id: 1,
    name: "Green Delight",
    type: "Vegan",
    cuisines: ["Vegan", "Salads", "Smoothies"],
    avgRating: 4.5,
    avgRatingString: "Four Point Five",
    totalRating: 1500,
    totalRatingString: "1.5k",
    address: {
      locality: "Connaught Place",
      city: "Delhi",
      state: "Delhi",
      pincode: 110001,
      country: "India",
    },
  },
  {
    id: 2,
    name: "Herbivore Heaven",
    type: "Vegan",
    cuisines: ["Vegan", "Italian", "Desserts"],
    avgRating: 4.8,
    avgRatingString: "Four Point Eight",
    totalRating: 2500,
    totalRatingString: "2.5k",
    address: {
      locality: "Hauz Khas",
      city: "Delhi",
      state: "Delhi",
      pincode: 110016,
      country: "India",
    },
  },
  {
    id: 3,
    name: "Veggie Feast",
    type: "Veg",
    cuisines: ["Indian", "Chinese", "Continental"],
    avgRating: 4.3,
    avgRatingString: "Four Point Three",
    totalRating: 1800,
    totalRatingString: "1.8k",
    address: {
      locality: "Saket",
      city: "Delhi",
      state: "Delhi",
      pincode: 110017,
      country: "India",
    },
  },
  {
    id: 4,
    name: "The Vegan Bistro",
    type: "Vegan",
    cuisines: ["Vegan", "Thai", "Mexican"],
    avgRating: 4.6,
    avgRatingString: "Four Point Six",
    totalRating: 2100,
    totalRatingString: "2.1k",
    address: {
      locality: "Vasant Kunj",
      city: "Delhi",
      state: "Delhi",
      pincode: 110070,
      country: "India",
    },
  },
  {
    id: 5,
    name: "Pure Veggie",
    type: "Veg",
    cuisines: ["South Indian", "North Indian", "Chinese"],
    avgRating: 4.2,
    avgRatingString: "Four Point Two",
    totalRating: 3200,
    totalRatingString: "3.2k",
    address: {
      locality: "Karol Bagh",
      city: "Delhi",
      state: "Delhi",
      pincode: 110005,
      country: "India",
    },
  },
  {
    id: 6,
    name: "Vegan Vibes",
    type: "Vegan",
    cuisines: ["Vegan", "Japanese", "Fusion"],
    avgRating: 4.7,
    avgRatingString: "Four Point Seven",
    totalRating: 2700,
    totalRatingString: "2.7k",
    address: {
      locality: "Chandni Chowk",
      city: "Delhi",
      state: "Delhi",
      pincode: 110006,
      country: "India",
    },
  },
  {
    id: 7,
    name: "Veg Delight",
    type: "Veg",
    cuisines: ["Italian", "Mexican", "Indian"],
    avgRating: 4.1,
    avgRatingString: "Four Point One",
    totalRating: 2000,
    totalRatingString: "2k",
    address: {
      locality: "Rohini",
      city: "Delhi",
      state: "Delhi",
      pincode: 110085,
      country: "India",
    },
  },
  {
    id: 8,
    name: "Plant Power",
    type: "Vegan",
    cuisines: ["Vegan", "Mediterranean", "Lebanese"],
    avgRating: 4.4,
    avgRatingString: "Four Point Four",
    totalRating: 3100,
    totalRatingString: "3.1k",
    address: {
      locality: "Dwarka",
      city: "Delhi",
      state: "Delhi",
      pincode: 110075,
      country: "India",
    },
  },
  {
    id: 9,
    name: "Herbal Essence",
    type: "Veg",
    cuisines: ["North Indian", "Continental", "Chinese"],
    avgRating: 4.0,
    avgRatingString: "Four",
    totalRating: 2200,
    totalRatingString: "2.2k",
    address: {
      locality: "Lajpat Nagar",
      city: "Delhi",
      state: "Delhi",
      pincode: 110024,
      country: "India",
    },
  },
  {
    id: 10,
    name: "Nature's Plate",
    type: "Vegan",
    cuisines: ["Vegan", "American", "Indian"],
    avgRating: 4.9,
    avgRatingString: "Four Point Nine",
    totalRating: 4500,
    totalRatingString: "4.5k",
    address: {
      locality: "Green Park",
      city: "Delhi",
      state: "Delhi",
      pincode: 110016,
      country: "India",
    },
  },
];

export default restaurants;
